# Generated by Django 4.1.4 on 2022-12-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("pass1", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=4000)),
                ("regdate", models.DateTimeField()),
                ("regcnt", models.IntegerField(default=0)),
                ("file1", models.CharField(max_length=300)),
            ],
        ),
    ]
