# Generated by Django 4.1.4 on 2022-12-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_regcnt_board_readcnt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board", name="regdate", field=models.DateTimeField(null=True),
        ),
    ]
